### ISSUE TITLE
BUG: KeyError: "Update keys don't match existing keys

### ISSUE THREAD

**Issue by wesleybowman** [wesleybowman/UTide#31]
An error gets thrown when solve is run:
```
coef = solve(time, u, v, lat, cnstit='auto',
               notrend=True, rmin=0.95, method='ols',
               nodiagn=True, linci=True, conf_int=True)
```
returns:
```
KeyError: "Update keys ['cnstit', 'linci', 'nodiagn', 'notrend', 'rmin'] don't match existing keys ['MC_n', 'Rayleigh_min', 'conf_int', 'constit', 'infer', 'method', 'nodal', 'phase', 'robust_kw', 'trend', 'white']"
```

Trying:
```
opts = dict(constit = 'auto',
                   notrend = True,
                   rmin = 0.95,
                   conf_int = 'linear',
                   method = 'ols',
                   nodiagn = True,
                   linci = True
                  )

coef = solve(time, u, v, lat=lat, **opts)
```

still results in the error. A more detailed error report is as follows:
```
Traceback (most recent call last):

  File "C:/Users/lisa/Desktop/My Work/test/pd0.py", line 456, in <module>

…
    coef = solve(time, u, v, lat=lat, **opts)

  File "c:\users\lisa\appdata\local\continuum\anaconda\lib\site-packages\utide-0.1b0.dev0-py2.7.egg\utide\_solve.py", line 143, in solve

    newopts = _process_opts(opts)

  File "c:\users\lisa\appdata\local\continuum\anaconda\lib\site-packages\utide-0.1b0.dev0-py2.7.egg\utide\_solve.py", line 33, in _process_opts

    newopts.update_values(strict=True, **opts)

  File "c:\users\lisa\appdata\local\continuum\anaconda\lib\site-packages\utide-0.1b0.dev0-py2.7.egg\utide\utilities.py", line 125, in update_values

    self._check_strict(strict, newkw)

  File "c:\users\lisa\appdata\local\continuum\anaconda\lib\site-packages\utide-0.1b0.dev0-py2.7.egg\utide\utilities.py", line 153, in _check_strict

    "Update keys %s don't match existing keys %s" % (bk, ek))

KeyError: "Update keys ['linci', 'nodiagn', 'notrend', 'rmin'] don't match existing keys ['MC_n', 'Rayleigh_min', 'conf_int', 'constit', 'infer', 'method', 'nodal', 'phase', 'robust_kw', 'trend', 'white']"
```

**Comment by efiring** [comment]
This is not a bug, it reflects evolution of the API.  See the docstring for `solve`.

**Comment by wesleybowman** [comment]
Do we have an example that I can get the user to try then? We might want to update the readme

**Comment by efiring** [comment]
Good point--I was not paying attention to the README.md.  I can update that later today.  In the meantime, see tests/test_solve.py  Refer the user to that and to the docstring.
