### ISSUE TITLE
Utide 0.2.3 incompatible with numpy 1.6.3 or greater

### ISSUE THREAD

**Issue by hadfieldnz** [wesleybowman/UTide#73]
I have utide 0.2.3 installed with Miniconda. With numpy 1.6.2, I can import utide with no problems. With numpy 1.6.3 or 1.6.4 I get the following:

```
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.16.3'
>>> import utide
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\markh\Miniconda3\envs\python37\lib\site-packages\utide\__init__.py", line 3, in <module>
    from ._solve import solve
  File "C:\Users\markh\Miniconda3\envs\python37\lib\site-packages\utide\_solve.py", line 9, in <module>
    from .harmonics import ut_E
  File "C:\Users\markh\Miniconda3\envs\python37\lib\site-packages\utide\harmonics.py", line 11, in <module>
    from ._ut_constants import ut_constants
  File "C:\Users\markh\Miniconda3\envs\python37\lib\site-packages\utide\_ut_constants.py", line 13, in <module>
    ut_constants = loadbunch(_ut_constants_fname, masked=False)
  File "C:\Users\markh\Miniconda3\envs\python37\lib\site-packages\utide\utilities.py", line 288, in loadbunch
    out[k] = _structured_to_bunch(xx[k], masked=masked)
  File "C:\Users\markh\Miniconda3\envs\python37\lib\site-packages\numpy\lib\npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "C:\Users\markh\Miniconda3\envs\python37\lib\site-packages\numpy\lib\format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

**Comment by wesleybowman** [comment]
Hmm, we had a similar issue recently: https://github.com/wesleybowman/UTide/issues/67

But I thought we had fixed that. Are you sure you are using the most recent version of UTide?

**Comment by efiring** [comment]
It looks like what is needed is just a release tag. This was fixed after v0.2.3 was released.

**Comment by ocefpaf** [comment]
We have a tag and there are packages on PyPI and conda-forge for 0.2.3.

https://pypi.org/project/UTide/0.2.3/

**Comment by efiring** [comment]
But that was before the pickle problem was fixed.
```
commit 5322b0b9fbc837e00d7e345d0b1d364ec278d54c (tag: v0.2.3)
Merge: 82fd9b7 7f89e70
Author: Filipe <ocefpaf@gmail.com>
Date:   Mon Apr 15 10:07:44 2019 -0300

    Merge pull request #66 from ocefpaf/modernize_cis

    Modernize CIs
```

**Comment by ocefpaf** [comment]
Ah. OK. Sorry. For some reason I thought that had this fix. Issuing a tag now.
